name: Docker Image CI

on:
  push:
    branches: [ master, main ]
  schedule:
    - cron:  '30 2 * * *'
  workflow_dispatch:
    inputs:
      name:
        description: 'Reason'
        required: true
        default: 'Why??'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
          - 3
          - 3.9.12
          - 3.10.5
          - 3.11.1
          - 3-3.12.2
          - 4.x
          - 4.1.9
          - latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Build and push latest
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        context: .
        platforms: linux/amd64,linux/arm64
        file: Dockerfile
        tags: davyinsa/mysql-backup-rotate:${{ matrix.version }}
        build-args: |
          VERSION=${{ matrix.version }}

    - name: Login to ALIYUN CR
      uses: docker/login-action@v3
      with:
        registry: registry.cn-hangzhou.aliyuncs.com
        username: ${{ secrets.ALIYUNCR_USERNAME }}
        password: ${{ secrets.ALIYUNCR_PASSWORD }}
    - name: Build and push to ALIYUN CR
      uses: docker/build-push-action@v5
      with:
        push: true
        context: .
        platforms: linux/amd64,linux/arm64
        file: "Dockerfile"
        tags: "registry.cn-hangzhou.aliyuncs.com/davyin/mysql-backup-rotate:${{ matrix.version }}"
        build-args: |
          VERSION=${{ matrix.version }}